### ISSUE TITLE
golangci-lint fails

### ISSUE THREAD

**Issue by wetneb** [mattermost/mattermost-plugin-starter-template#204]
I followed the Getting Started instructions from the README and got the following error when running `make` as instructed:
```
...
Running golangci-lint
/usr/bin/go vet ./...
/home/user/my-plugin/bin/golangci-lint run ./...
ERRO [runner] Panic: atomicalign: package "main" (isInitialPkg: true, needAnalyzeSource: true): runtime error: invalid memory address or nil pointer dereference: goroutine 6450 [running]:
runtime/debug.Stack()
	/usr/lib/go-1.22/src/runtime/debug/stack.go:24 +0x5e
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1()
	/home/user/go/pkg/mod/github.com/golangci/golangci-lint@v1.51.1/pkg/golinters/goanalysis/runner_action.go:102 +0x13e
panic({0x15d5de0?, 0x217d330?})
	/usr/lib/go-1.22/src/runtime/panic.go:770 +0x132
go/types.(*StdSizes).Sizeof(0x0, {0x19b1fb0, 0x2194940})
	/usr/lib/go-1.22/src/go/types/sizes.go:228 +0x30f
golang.org/x/tools/go/analysis/passes/atomicalign.run(0xc01581aff0)
	/home/user/go/pkg/mod/golang.org/x/tools@v0.5.0/go/analysis/passes/atomicalign/atomicalign.go:33 +0x52
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyze(0xc0022fffd0)
	/home/user/go/pkg/mod/github.com/golangci/golangci-lint@v1.51.1/pkg/golinters/goanalysis/runner_action.go:188 +0x98a
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func2()
	/home/user/go/pkg/mod/github.com/golangci/golangci-lint@v1.51.1/pkg/golinters/goanalysis/runner_action.go:106 +0x17
github.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc001b52dc0, {0x176d678, 0xb}, 0xc002e3d748)
	/home/user/go/pkg/mod/github.com/golangci/golangci-lint@v1.51.1/pkg/timeutils/stopwatch.go:111 +0x44
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe(0xc002437c80?)
	/home/user/go/pkg/mod/github.com/golangci/golangci-lint@v1.51.1/pkg/golinters/goanalysis/runner_action.go:105 +0x7a
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze.func2(0xc0022fffd0)
	/home/user/go/pkg/mod/github.com/golangci/golangci-lint@v1.51.1/pkg/golinters/goanalysis/runner_loadingpackage.go:80 +0xa8
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze in goroutine 160
	/home/user/go/pkg/mod/github.com/golangci/golangci-lint@v1.51.1/pkg/golinters/goanalysis/runner_loadingpackage.go:75 +0x1e5 
WARN [runner] Can't run linter goanalysis_metalinter: goanalysis_metalinter: atomicalign: package "main" (isInitialPkg: true, needAnalyzeSource: true): runtime error: invalid memory address or nil pointer dereference 
ERRO Running error: 1 error occurred:
	* can't run linter goanalysis_metalinter: goanalysis_metalinter: atomicalign: package "main" (isInitialPkg: true, needAnalyzeSource: true): runtime error: invalid memory address or nil pointer dereference
 
```

Running on Debian testing, go version go1.22.4 linux/amd64

**Comment by daerlnaxe** [comment]
MakeFile still to have the 1.51.1 version
